/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dessin;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author moham
 */
public class TestDessin extends javax.swing.JFrame {

    //attributs
    private Bille maBille1;
    private Bille maBille2;
    private int billeSelect;
    
    public TestDessin() {
        initComponents();
        this.maBille1=new Bille(50,50,20);
        this.maBille2=new Bille(150,200,30);
        this.billeSelect=1;
        this.maBille1.setCouleur(Color.GREEN);
        this.maBille2.setCouleur(Color.BLUE);
        //les billes seront affichées par la méthode paint
        
        
        
    }
    @Override
    //surcharge de la méthode paint(hérité de la JFrame)
    public void paint(Graphics g){
        super.paint(g);//appel de la méthode de paint de la classe ancetre , ici JFrame
        //on affiche les billes
        this.maBille1.dessineBille(PanDessin);
        this.maBille2.dessineBille(PanDessin);
        
    }
    
    
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BHaut = new javax.swing.JButton();
        BGauche = new javax.swing.JButton();
        BDroit = new javax.swing.JButton();
        BBas = new javax.swing.JButton();
        BBille = new javax.swing.JButton();
        PanDessin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 12)); // NOI18N
        jLabel1.setText("Déplace les billes en cliquant dans le panneau ou avec les boutons !");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        BHaut.setText("Haut");
        BHaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHautActionPerformed(evt);
            }
        });
        jPanel2.add(BHaut);

        BGauche.setText("Gauche");
        BGauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGaucheActionPerformed(evt);
            }
        });
        jPanel2.add(BGauche);

        BDroit.setText("Droite");
        BDroit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDroitActionPerformed(evt);
            }
        });
        jPanel2.add(BDroit);

        BBas.setText("Bas");
        BBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBasActionPerformed(evt);
            }
        });
        jPanel2.add(BBas);

        BBille.setForeground(new java.awt.Color(51, 255, 51));
        BBille.setText("Bille 1");
        BBille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBilleActionPerformed(evt);
            }
        });
        jPanel2.add(BBille);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        PanDessin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanDessin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanDessinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanDessinLayout = new javax.swing.GroupLayout(PanDessin);
        PanDessin.setLayout(PanDessinLayout);
        PanDessinLayout.setHorizontalGroup(
            PanDessinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        PanDessinLayout.setVerticalGroup(
            PanDessinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        getContentPane().add(PanDessin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BHautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHautActionPerformed
        if(billeSelect==1)
        this.maBille1.deplaceBille(0,-10);
        else
        this.maBille2.deplaceBille(0, -10);
        //on redessine
        this.repaint();//va appeler la méthode paint
    }//GEN-LAST:event_BHautActionPerformed

    private void BBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBasActionPerformed
        if(billeSelect==1)
        this.maBille1.deplaceBille(0,10);
        else
        this.maBille2.deplaceBille(0, 10);
        //on redessine
        this.repaint();//va appeler la méthode paint
    }//GEN-LAST:event_BBasActionPerformed

    private void BDroitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDroitActionPerformed
        if(billeSelect==1)
        this.maBille1.deplaceBille(10,0);
        else
        this.maBille2.deplaceBille(10, 0);
        //on redessine
        this.repaint();//va appeler la méthode paint
    }//GEN-LAST:event_BDroitActionPerformed

    private void BGaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGaucheActionPerformed
        if(billeSelect==1)
        this.maBille1.deplaceBille(-10,0);
        else
        this.maBille2.deplaceBille(-10, 0);
        //on redessine
        this.repaint();//va appeler la méthode paint
    }//GEN-LAST:event_BGaucheActionPerformed

    private void BBilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBilleActionPerformed

        if(billeSelect==1){
            billeSelect=2;
            BBille.setForeground(this.maBille1.getCouleur());
            BBille.setText("Bille 1");
        }
        else
            {
            billeSelect=1;
            BBille.setForeground(this.maBille2.getCouleur());
            BBille.setText("Bille 2");
            }
    }//GEN-LAST:event_BBilleActionPerformed

    private void PanDessinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanDessinMouseClicked
        //evt permet de récupérer les coordonées souris
        int mx=evt.getX();
        int my=evt.getY();
        if(billeSelect==1){
            this.maBille1.setX(mx);
            this.maBille1.setY(my);
           
        }
        else {
            this.maBille2.setX(mx);
            this.maBille2.setY(my);
            
        }
        //on redessine
        this.repaint();
    }//GEN-LAST:event_PanDessinMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestDessin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestDessin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestDessin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestDessin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestDessin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBas;
    private javax.swing.JButton BBille;
    private javax.swing.JButton BDroit;
    private javax.swing.JButton BGauche;
    private javax.swing.JButton BHaut;
    private javax.swing.JPanel PanDessin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
