/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package palette.des.couleurs;

import java.awt.Color;
import javax.swing.JButton;
import java.awt.*;

/**
 *
 * @author moham
 */
public class PaletteCouleur extends javax.swing.JFrame {

    //pas de nouvel attribut à ajouter
    //on utilise directement les couleurs des boutons
    //consturcteur
    public PaletteCouleur() {
        initComponents();//description de l'interface crée par l'EDI
        initPanneau();//méthode pour crée les boutons dans le panneau
    }
    
    public void initPanneau(){
        //boucle pour crée 400 boutons
        for(int i=0;i<400;i++)
        {//création d'un bouton
            JButton bouton = new JButton();
            //génération d'une couleur aléatoire
            int rouge = (int)(Math.random()*256);
            int vert = (int)(Math.random()*256);
            int bleu = (int)(Math.random()*256);
            Color coul = new Color(rouge,vert,bleu);
            //on affecte la couleur au bouton
            bouton.setBackground(coul);
            //on abonne le bouton, à un écouteur
            //pour q'il soit cliquable (ActionEvent)
            bouton.addActionListener(new java.awt.event.ActionListener()
                {public void actionPerformed(java.awt.event.ActionEvent evt)
                        
                {boutonActionPerformed(evt);//méthode exécutée quand on clique sur le bouton
                
                }
            });
            //on ajoute le bouton dans le panneau
             Panneau.add(bouton);
                    }
            
    
             
        
    
    }
    //gestionnaire du clic sur un bouton(un des 400 boutons)
    private void boutonActionPerformed(java.awt.event.ActionEvent evt){
        //on récupère le bouton qui a déclenché l'action
        JButton bt = (JButton)evt.getSource();
        //on récupère sa couleur
        Color coul = bt.getBackground();
        //on récupère tous les boutons et on change leurs couleurs
        for(int i=0;i<400;i++)
        {JButton btt = (JButton)Panneau.getComponent(i);
         //on modifie la couleur
         btt.setBackground(coul);
            
        }
        String r=String.valueOf(coul.getRed());
        String v=String.valueOf(coul.getGreen());
        String b=String.valueOf(coul.getBlue());
        
        Rouge.setText(r);
        Vert.setText(v);
        Bleu.setText(b);
        
    
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PDroit = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        LVide = new javax.swing.JLabel();
        MRouge = new javax.swing.JLabel();
        Rouge = new javax.swing.JLabel();
        MVert = new javax.swing.JLabel();
        Vert = new javax.swing.JLabel();
        MBleu = new javax.swing.JLabel();
        Bleu = new javax.swing.JLabel();
        Nouveau = new javax.swing.JButton();
        Panneau = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PDroit.setLayout(new java.awt.GridLayout(10, 1));

        LTitre.setText("Couleur");
        PDroit.add(LTitre);
        PDroit.add(LVide);

        MRouge.setText("Rouge");
        PDroit.add(MRouge);
        PDroit.add(Rouge);

        MVert.setText("Vert");
        PDroit.add(MVert);
        PDroit.add(Vert);

        MBleu.setText("Bleu");
        PDroit.add(MBleu);
        PDroit.add(Bleu);

        Nouveau.setText("Nouveau");
        Nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NouveauActionPerformed(evt);
            }
        });
        PDroit.add(Nouveau);

        getContentPane().add(PDroit, java.awt.BorderLayout.EAST);

        Panneau.setLayout(new java.awt.GridLayout(20, 20));
        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NouveauActionPerformed
        for(int i=0;i<400;i++)
        {JButton bt = (JButton)Panneau.getComponent(i);
         int rouge = (int)(Math.random()*256);
         int vert = (int)(Math.random()*256);
         int bleu = (int)(Math.random()*256);
         bt.setBackground(new Color(rouge,vert,bleu));
         
        }
        Rouge.setText("");
        Vert.setText("");
        Bleu.setText("");
    }//GEN-LAST:event_NouveauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaletteCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaletteCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaletteCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaletteCouleur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaletteCouleur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bleu;
    private javax.swing.JLabel LTitre;
    private javax.swing.JLabel LVide;
    private javax.swing.JLabel MBleu;
    private javax.swing.JLabel MRouge;
    private javax.swing.JLabel MVert;
    private javax.swing.JButton Nouveau;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel Rouge;
    private javax.swing.JLabel Vert;
    // End of variables declaration//GEN-END:variables
}
